---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by camin-pc.
--- DateTime: 2020/1/15 11:29
---

local uri_args = ngx.req.get_uri_args()
local productId = uri_args["productId"]
--获取链接地址 和 productId参数
local hosts = {"172.16.95.145","172.16.95.146","172.16.95.147"}
local hash = ngx.crc32_long(productId)
local hosts_cnt = #hosts
local index = (hash % hosts_cnt) + 1
--分发的主机地址 对参数取模
backend = "http://"..hosts[index]

local method = uri_args["method"]
local requestBody = "/"..method.."?productId="..productId

local http = require("resty.http")
local httpc = http.new()

local resp,err = httpc:request_uri(backend,{
    method = "GET",
    path = requestBody
})

if not resp then
    ngx.say("requst err:",err)
    return
end

ngx.say(resp.body)
httpc:close()